---
title: "Thesis citation test"
author: "Danae Bouwer"
date: "25/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#============================================================================================================================================================
##Setting up test table and loading package
#============================================================================================================================================================

library(readxl)
TestDataFrame = read_excel("TestDataFrame.xlsx")
library(rscopus)

#============================================================================================================================================================
##Get Article name, put it into function, get data, put into output dataframe
#============================================================================================================================================================

CitationData = c()

##Start Loop
for(i in 1:nrow(TestDataFrame)){
articleTitle = paste0('Title(',TestDataFrame[i,'Article Title'],')')

#============================================================================================================================================================
##Catch any 404 errors (404 error is if Scopus cannot show any results)
#============================================================================================================================================================  
CatchError404 = tryCatch(
    
  expr = {
            #rScopus function to get the data from Scopus
    
            res = scopus_search(query = articleTitle, api_key = "44f055d2666f0d63b928f6d10e2f77d2",view = "COMPLETE", max_count = 1,count = 1)
          },
    
  error = function(error_message){ 
            message("Error occured in Scopus")
            IsError = print(error_message)
          }
)

IsError404 = unlist(CatchError404)[1]$message

if (is.null(IsError404) == FALSE){
  
  
                
                NewEntry = c(FALSE,
                              NA,
                              NA,
                              TestDataFrame[i,'Article Title'],
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA, 
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA)
                
                CitationData = rbind(CitationData,NewEntry)
  
 } else {
    
#============================================================================================================================================================
##If there was no 404 error and the article was either in Scopus or Result set was empty
#============================================================================================================================================================

#rScopus function to get the data from Scopus
   
res = scopus_search(query = articleTitle, api_key = "44f055d2666f0d63b928f6d10e2f77d2",view = "COMPLETE", max_count = 1,count = 1)


#Filtering for 'Result set was empty' errors

IsErrorEmptyResultSet = try(get("error", res$entries[[1]][2]))

if (IsErrorEmptyResultSet == "Result set was empty"){
  
                
                NewEntry = c(FALSE,
                              NA,
                              NA,
                              TestDataFrame[i,'Article Title'],
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA,
                              NA)
                
                CitationData = rbind(CitationData,NewEntry)
                  
  } else {
    
###Defining available variables
    
##Article Information
    
    ArtclID = res$entries[[1]]$`dc:identifier`
    ArtclID[is.null(ArtclID)] = NA
    
    Artcleid = res$entries[[1]]$eid
    Artcleid[is.null(Artcleid)] = NA
    
    ArtclDOI = res$entries[[1]]$`prism:doi`
    ArtclDOI[is.null(ArtclDOI)] = NA
    
    ArtclTitle = TestDataFrame[i,'Article Title']
    ArtclTitle[is.null(ArtclTitle)] = NA
    
    PublicationName = res$entries[[1]]$`prism:publicationName`
    PublicationName[is.null(PublicationName)] = NA
    
    Publishissn = unlist(res$entries[[1]]$`prism:issn`)
    Publishissn[is.null(Publishissn)] = NA
    
    PublishPageRange = res$entries[[1]]$`prism:pageRange`
    PublishPageRange[is.null(PublishPageRange)] = NA
    
    PublishCoverDate = res$entries[[1]]$`prism:coverDate`
    PublishCoverDate[is.null(PublishCoverDate)] = NA
    
    PUblishType = res$entries[[1]]$`prism:aggregationType`
    PUblishType[is.null(PUblishType)] = NA
    
    PublishSubType = res$entries[[1]]$subtype
    PublishSubType[is.null(PublishSubType)] = NA
    
    PublishSubTypeDescr = res$entries[[1]]$subtypeDescription
    PublishSubTypeDescr[is.null(PublishSubTypeDescr)] = NA
    
    PublishVolume = res$entries[[1]]$`prism:volume`
    PublishVolume[is.null(PublishVolume)] = NA
    
    ArticleDescr = res$entries[[1]]$`dc:description`
    ArticleDescr[is.null(ArticleDescr)] = NA
    
    CitedbyCount = res$entries[[1]]$`citedby-count`
    CitedbyCount[is.null(CitedbyCount)] = NA
    
    AuthorCount = res$entries[[1]]$`author-count`$`$`
    AuthorCount[is.null(AuthorCount)] = NA
    AuthorCount = as.numeric(AuthorCount)
    
#============================================================================================================================================================
##Account for multiple authors per article   
#============================================================================================================================================================

##If there is multiple authors for the article
if (AuthorCount > 1){ 
  
  for(j in 1:AuthorCount){
    
##Author Info
    
    AuthorName = res$entries[[1]]$author[[j]]$authname
    AuthorName[is.null(AuthorName)] = NA
    
    Initial = res$entries[[1]]$author[[j]]$initials
    Initial[is.null(Initial)] = NA
    
    Firstname = res$entries[[1]]$author[[j]]$`given-name`
    Firstname[is.null(Firstname)] = NA
    
    Lastname = res$entries[[1]]$author[[j]]$surname
    Lastname[is.null(Lastname)] = NA
    
    AuthorID = res$entries[[1]]$author[[j]]$authid
    AuthorID[is.null(AuthorID)] = NA
    
    
##Affiliation Info
    
    ##Handle cases where some Affiliation info is missing
    
    IsErrorSubscriptOOB = try(get("error", res$entries[[1]]$affiliation[[j]]$affilname))[1]
    
    if(IsErrorSubscriptOOB == "Error in res$entries[[1]]$affiliation[[j]] : subscript out of bounds\n"){
      AffilID = NA
      Affilname = NA
      Affilcity = NA
      Affilcountry = NA
    } else {
    
    AffilID = res$entries[[1]]$affiliation[[j]]$afid
    AffilID[is.null(AffilID)] = NA
    
    Affilname = res$entries[[1]]$affiliation[[j]]$affilname
    Affilname[is.null(Affilname)] = NA
    
    Affilcity = res$entries[[1]]$affiliation[[j]]$`affiliation-city`
    Affilcity[is.null(Affilcity)] = NA
    
    Affilcountry = res$entries[[1]]$affiliation[[j]]$`affiliation-country`
    Affilcountry[is.null(Affilcountry)] = NA
    
    }

###Creating the vector that populates the dataframe
    
                 NewEntry = c(TRUE,
                              ArtclID,
                              Artcleid,
                              ArtclDOI,
                              ArtclTitle,
                              PublicationName,
                              Publishissn,
                              PublishPageRange,
                              PublishCoverDate,
                              PUblishType,
                              PublishSubType,
                              PublishSubTypeDescr,
                              PublishVolume,
                              ArticleDescr,
                              CitedbyCount,
                              AuthorName,
                              Initial,
                              Firstname,
                              Lastname,
                              AuthorID,
                              AffilID,
                              Affilname,
                              Affilcity,
                              Affilcountry)
                 
                  CitationData = rbind(CitationData,NewEntry)
    
  }

##If there is only one Author  
  
  } else {
  
##Author Info
    
    AuthorName = res$entries[[1]]$author[[1]]$authname
    AuthorName[is.null(AuthorName)] = NA
    
    Initial = res$entries[[1]]$author[[1]]$initials
    Initial[is.null(Initial)] = NA
    
    Firstname = res$entries[[1]]$author[[1]]$`given-name`
    Firstname[is.null(Firstname)] = NA
    
    Lastname = res$entries[[1]]$author[[1]]$surname
    Lastname[is.null(Lastname)] = NA
    
    AuthorID = res$entries[[1]]$author[[1]]$authid
    AuthorID[is.null(AuthorID)] = NA
    
    
##Affiliation Info
    
    AffilID = res$entries[[1]]$affiliation[[1]]$afid
    AffilID[is.null(AffilID)] = NA
    
    Affilname = res$entries[[1]]$affiliation[[1]]$affilname
    Affilname[is.null(Affilname)] = NA
    
    Affilcity = res$entries[[1]]$affiliation[[1]]$`affiliation-city`
    Affilcity[is.null(Affilcity)] = NA
    
    Affilcountry = res$entries[[1]]$affiliation[[1]]$`affiliation-country`
    Affilcountry[is.null(Affilcountry)] = NA
    

###Creating the vector that populates the dataframe
    
                 NewEntry = c(TRUE,
                              ArtclID,
                              Artcleid,
                              ArtclDOI,
                              ArtclTitle,
                              PublicationName,
                              Publishissn,
                              PublishPageRange,
                              PublishCoverDate,
                              PUblishType,
                              PublishSubType,
                              PublishSubTypeDescr,
                              PublishVolume,
                              ArticleDescr,
                              CitedbyCount,
                              AuthorName,
                              Initial,
                              Firstname,
                              Lastname,
                              AuthorID,
                              AffilID,
                              Affilname,
                              Affilcity,
                              Affilcountry)
  
                CitationData = rbind(CitationData,NewEntry)
      }
    
    }
 
  }   

##CitationData = rbind(CitationData,NewEntry)

}


##Adding column headers

CitationData = as.data.frame(CitationData)
names(CitationData) = c("In Scopus", "Article Scopus ID", "Article eid","Article DOI", "Article Title", "Publication Name", "Publish issn", "Publish Page Range", "Publish Cover Date", "PUblish Type", "Publish SubType", "Publish SubType Description", "Publish Volume", "Article Description", "Article Cited by Count","Author Name", "Initial", "Firstname", "Lastname", "Author Scopus ID", "Affiliation ID", "Affiliation name", "Affiliation city", "Affiliation country")



```

```{r}

##Testing out functions

res = complete_multi_author_info(au_id = c('7003483273','36877553300'),api_key = "44f055d2666f0d63b928f6d10e2f77d2")
res$entries[[1]]$link[[2]]$`@href`
df = gen_entries_to_df(res$entries)
head(df$df)


##Using PlumX to get information on the article
set_api_key("44f055d2666f0d63b928f6d10e2f77d2")
type = "elsevierId"
value = "9-s2.0-36877553300"
res = plumx_metrics(value, type)

res = scopus_search(query = 'title(Cooperation and Bounded Recall,)', api_key = "44f055d2666f0d63b928f6d10e2f77d2",view = "COMPLETE", max_count = 1,count = 1)
Affilname = res$entries[[1]]$affiliation[[3]]$affilname
j = 3
IsErrorSubscriptOOB = try(get("error", res$entries[[1]]$affiliation[[j]]$affilname))[1]
IsErrorEmptyResultSet = try(get("error", res$entries[[1]][2]))


##this gives number of documents by author, breakdown of the total docs (like what portion falls in which field of study)
meh = get_complete_author_info(au_id = "36877553300",api_key = "44f055d2666f0d63b928f6d10e2f77d2")

meh$content

generic_elsevier_api(query = "https://api.elsevier.com/metrics/metrics?metrics=ScholarlyOutput%2CCitedPublications&authors=6701858763%2C20433296900&yearRange=5yrs&includeSelfCitations=true&byYear=true&includedDocs=AllPublicationTypes&journalImpactType=CiteScore&showAsFieldWeighted=false&indexType=hIndex",type = "search", search_type = "author",
api_key = "44f055d2666f0d63b928f6d10e2f77d2")
 https://api.elsevier.com/metrics/metrics?metrics=ScholarlyOutput%2CCitedPublications&authors=6701858763%2C20433296900&yearRange=5yrs&includeSelfCitations=true&byYear=true&includedDocs=AllPublicationTypes&journalImpactType=CiteScore&showAsFieldWeighted=false&indexType=hIndex

```


